layout_spectrum: 0.6559390413519548
typography_spectrum: 0.2686354813284914
color:
  brandColors:
    - '#73603D'
    - '#BF8A49'
    - '#F2CA80'
    - '#5E5A59'
    - '#0D0D0D'
  brandStrength: 0.42499037834170206
  lightness: 0.4777380603017968
  saturation: 0.296239141759435
  rhythmicContrast: 0.5351150860029762
coverPrefs:
  filter: false
name: bam@bam.com
opengraph:
  type: ''
  appId: ''
purpose:
  - type: contact
    label: 'Bam @ Bam '
    url: 'mailto:bam.kalliope@gmail.com'
title: Bam @ Bam
description: >-
  Musicians Collaboration With the Best Master(s) their Influence(s) and Current
  Musical Projects and Performance Forum Welcome. 
author:
  name: Bam Bam
  url: bam@bam.com
  email: bam.kalliope@gmail.com
content_rating:
  adult: false
content: []
github: true
